name: elastic_apm_php
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version deploy.'
        required: true

jobs:
  build_x86-64:
    name: build-agent-library-x86-64
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHITECTURE: linux-x86-64
    steps:
      - uses: actions/checkout@v3
        with:
          repository: elastic/apm-agent-php
          ref: ${{ github.event.inputs.version }}
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Default buildx
        run: docker buildx install

      - name: Build
        run: make -f .ci/Makefile build

      - uses: actions/upload-artifact@v3
        with:
          name: package-parts-linux-x86-64
          path: |
            agent/native/_build/linux-x86-64-release/ext/elastic_apm*.so

  build_arm64:
    name: build-agent-library-arm64
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHITECTURE: linux-arm64
    steps:
      - uses: actions/checkout@v3
        with:
          repository: elastic/apm-agent-php
          ref: ${{ github.event.inputs.version }}
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Default buildx
        run: docker buildx install

      - name: Build
        run: make -f .ci/Makefile build

      - uses: actions/upload-artifact@v3
        with:
          name: package-parts-linux-arm64
          path: |
            agent/native/_build/linux-arm64-release/ext/elastic_apm*.so
