name: node
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version deploy.'
        required: true

jobs:
  v22:
    runs-on: ubuntu-22.04
    name: v22
    if: ${{ (github.event.inputs.version == '22') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-22
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:22
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v21:
    runs-on: ubuntu-22.04
    name: v21
    if: ${{ (github.event.inputs.version == '21') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-21
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:21
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v20:
    runs-on: ubuntu-22.04
    name: v20
    if: ${{ (github.event.inputs.version == '20') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-20
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:20
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v20-sshd:
    runs-on: ubuntu-22.04
    name: v20-sshd
    if: ${{ (github.event.inputs.version == '20-sshd') || (github.event.inputs.version == 'sshd') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-20-sshd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:20-sshd

  # v19:
  #   runs-on: ubuntu-22.04
  #   name: v19
  #   if: ${{ (github.event.inputs.version == '19') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ${{ secrets.DOCKER_REPO }}
  #         token: ${{ secrets.GH_TOKEN }}
  #         path: .
  #         sparse-checkout: images

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3


  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  #     - name: Increase swapfile
  #       run: |
  #         sudo swapoff -a
  #         sudo fallocate -l 8G /swapfile
  #         sudo chmod 600 /swapfile
  #         sudo mkswap /swapfile
  #         sudo swapon /swapfile
  #         sudo swapon --show

  #     - name: Build and publish
  #       uses: docker/build-push-action@v6
  #       env:
  #         DOCKER_BUILD_SUMMARY: false
  #       with:
  #         context: ./images/node
  #         file: ./images/node/Dockerfile-19
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:19
  #         build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v18:
    runs-on: ubuntu-22.04
    name: v18
    if: ${{ (github.event.inputs.version == '18') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-18
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:18
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v18-sshd:
    runs-on: ubuntu-22.04
    name: v18-sshd
    if: ${{ (github.event.inputs.version == '18-sshd') || (github.event.inputs.version == 'sshd') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-18-sshd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:18-sshd

  v16:
    runs-on: ubuntu-22.04
    name: v16
    if: ${{ (github.event.inputs.version == '16') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-16
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:16
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v16-sshd:
    runs-on: ubuntu-22.04
    name: v16-sshd
    if: ${{ (github.event.inputs.version == '16-sshd') || (github.event.inputs.version == 'sshd') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-16-sshd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:16-sshd
  
  v14:
    runs-on: ubuntu-22.04
    name: v14
    if: ${{ (github.event.inputs.version == '14') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-14
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:14
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v14-sshd:
    runs-on: ubuntu-22.04
    name: v14-sshd
    if: ${{ (github.event.inputs.version == '14-sshd') || (github.event.inputs.version == 'sshd') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-14-sshd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:14-sshd

  v10:
    runs-on: ubuntu-22.04
    name: v10
    if: ${{ (github.event.inputs.version == '10') || (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-10
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:10
          build-args: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

  v10-sshd:
    runs-on: ubuntu-22.04
    name: v10-sshd
    if: ${{ (github.event.inputs.version == '10-sshd') || (github.event.inputs.version == 'sshd') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./images/node
          file: ./images/node/Dockerfile-10-sshd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node:10-sshd