name: php-nginx-sshd
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version deploy.'
        required: true

jobs:
  v8_2:
    runs-on: ubuntu-latest
    name: v8.2
    if: ${{ (github.event.inputs.version == '8.2') || (github.event.inputs.version == 'release') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./images/php-nginx-sshd
          file: ./images/php-nginx-sshd/Dockerfile-8.2
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:8.2-nginx-sshd

  v8_1:
    runs-on: ubuntu-latest
    name: v8.1
    if: ${{ (github.event.inputs.version == '8.1') || (github.event.inputs.version == 'release') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./images/php-nginx-sshd
          file: ./images/php-nginx-sshd/Dockerfile-8.1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:8.1-nginx-sshd

  v7_4:
    runs-on: ubuntu-latest
    name: v7.4
    if: ${{ (github.event.inputs.version == '7.4') || (github.event.inputs.version == 'release') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./images/php-nginx-sshd
          file: ./images/php-nginx-sshd/Dockerfile-7.4
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:7.4-nginx-sshd

  v7_3:
    runs-on: ubuntu-latest
    name: v7.3
    if: ${{ (github.event.inputs.version == '7.3') || (github.event.inputs.version == 'release') || (github.event.inputs.version == '*') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v3
        with:
          context: ./images/php-nginx-sshd
          file: ./images/php-nginx-sshd/Dockerfile-7.3
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm:7.3-nginx-sshd