name: php
on:
  workflow_dispatch:
    inputs:
      php:
        description: "PHP version (vd: 8.1, 8.2, 8.3 or *)"
        required: true
        default: "*"
      variant:
        description: "PHP variant: cli, fpm or *"
        required: true
        default: "*"

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
      variants: ${{ steps.set-matrix.outputs.variants }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          INPUT_PHP="${{ github.event.inputs.php }}"
          INPUT_VARIANT="${{ github.event.inputs.variant }}"

          ALL_VERSIONS='5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1 8.2 8.3 8.4'
          if [ "$INPUT_PHP" = "*" ]; then
            VERSIONS=($ALL_VERSIONS)
          else
            read -ra VERSIONS <<< "$INPUT_PHP"
          fi

          if [ "$INPUT_VARIANT" = "*" ]; then
            VARIANTS=("cli" "fpm")
          else
            VARIANTS=($INPUT_VARIANT)
          fi

          VERSIONS_JSON=$(printf '%s\n' "${VERSIONS[@]}" | jq -R . | jq -s -c .)
          VARIANTS_JSON=$(printf '%s\n' "${VARIANTS[@]}" | jq -R . | jq -s -c .)

          echo "versions=$VERSIONS_JSON" >> $GITHUB_OUTPUT
          echo "variants=$VARIANTS_JSON" >> $GITHUB_OUTPUT

  build:
    needs: docker-build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.docker-build.outputs.versions) }}
        variant: ${{ fromJson(needs.docker-build.outputs.variants) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          push: true
          context: ./images/php
          file: ./images/php/Dockerfile-${{ matrix.variant }}-${{ matrix.php }}
          platforms: linux/amd64,linux/arm64
          tags: >-
            ${{ matrix.variant == 'fpm'
                && format('{0}/php-fpm:{1}', secrets.DOCKERHUB_USERNAME, matrix.php)
                || format('{0}/php-fpm:{1}-{2}', secrets.DOCKERHUB_USERNAME, secrets.DOCKERHUB_REPO, matrix.php, matrix.variant) }}
