name: shopify-matrix
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version deploy.'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.version == 'node') || (github.event.inputs.version == '*') }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "18"
          - "20"
          - "22"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_NO_SUMMARY: true
        with:
          context: ./images/shopify
          file: ./images/shopify/Dockerfile-matrix
          platforms: linux/amd64,linux/arm64
          build-args: NODE_VERSION=${{ matrix.node_version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopify:node-${{ matrix.node_version }}

  ssh:
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.version == 'ssh') || (github.event.inputs.version == '*') }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "18"
          - "20"
          - "22"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DOCKER_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: .
          sparse-checkout: images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show

      - name: Build and publish
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_NO_SUMMARY: true
        with:
          context: ./images/shopify
          file: ./images/shopify/Dockerfile-matrix-ssh
          platforms: linux/amd64,linux/arm64
          build-args: NODE_VERSION=${{ matrix.node_version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopify:node-${{ matrix.node_version }}-ssh
